apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: default
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJabkpoYm1ObGMyTmhZblZ5WjJWMmFXNDZaMmh3WHpKTk1qaGtiSEZqU2pZM00wbDVOR0V4VTJKWU5tbFJRV1JYY1daMlNUQlRORloxTUE9PSIKICAgICAgICB9CiAgICB9Cn0=
type: kubernetes.io/dockerconfigjson